# Python Variables

## Numbers

Python acts like a calculator - you can type expression and it will return a value. Expression synthax is straightforward

In [ ]:
2+2

4

In [1]:
50 - 5*6

20

In [2]:
8/5 # division always returns a floating point number

1.6

The integer numbers (2, 20, 40) have type **int**, the ones with fractinal part (5.6, 3.2) have type **float**. <br>
To do **floor division** and get an integer result you can use the *//* operator.<br>
To calculate reminder we can use *%*.

In [3]:
17/3 # classic division returns a float 5.(6)
17//3 # floor division discards the fractional part 5
17%3 # the % operator returns the remainder of the division 2
5**2 # 5 squared

25

There is also a full support for floating point - operators with mixed operands convert the integer operand to floating point:

In [4]:
4 * 3.75 - 1

14.0

In addition to int and float, Python supports other types of numbers, such as Decimal and Fraction.  <br>
Python also has built-in support for complex numbers, and uses the j or J suffix to indicate the imaginary part (e.g. 3+5j).

## Text

Python can manipulate text, as well as numbers. The type is **str** (string). The string can be enclosed in sinqle quotes or double quotes.

In [5]:
'single quotes'
"double quotes"

'double quotes'

To quote a quote, we need to escape it by preceding with \ sign. Alternatively, we can also use other type of quotation marks:

In [6]:
'doesn\'t' # use \' to escape the single quote...
"doesn't" # ...or use double quotes instead
'"Yes," they said.'
"\"Yes,\" they said."

'"Yes," they said.'

The print() function produces a more readable output, by omitting the enclosing quotes and by printing escaped and special characters:

In [7]:
s = 'First line.\nSecond line.'  # \n means newline
s  # without print(), special characters are included in the string

'First line.\nSecond line.'

In [8]:
print(s)  # with print(), special characters are interpreted

First line.
Second line.


If you don’t want characters prefaced by \ to be interpreted as special characters, you can use raw strings by adding an r before the first quote:

In [9]:
print('C:some\name')  # here \n means newline!

C:some
ame


In [10]:
print(r'C:\some\name')  # note the r before the quote

C:\some\name


String literals can span multiple lines. One way is using triple-quotes: """...""" or '''...'''. End-of-line characters are automatically included in the string, but it’s possible to prevent this by adding a \ at the end of the line. In the following example, the initial newline is not included:

In [11]:
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")

Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



Strings can also be concatenated with **+** operator, and repeated with **"*"** operator

In [12]:
5* 'paw' + 'el'

'pawpawpawpawpawel'

In [13]:
# two or more string literals (i.e. the ones enclosed between quotes) next to each other are automatically concatenated.
'Py' 'thon'
# note that this only works with two literals though, not with variables or expressions

'Python'

Strings can be indexed (subscripted), with the first character having index 0. There is no separate character type; a character is simply a string of size one:

In [14]:
word = 'Python'
word[0]  # character in position 0

'P'

In [15]:
# indices may also be negative numbers, to start counting from the right
# note that since -0 is the same as 0, negative indices start from -1.
print(word[-1])  # last character
print(word[-2])  # second-last character
print(word[-6])

n
o
P


In addition to indexing, slicing is also supported. While indexing is used to obtain individual characters, slicing allows you to obtain a substring:

In [16]:
print(word[0:2])  # characters from position 0 (included) to 2 (excluded)
print(word[2:5])  # characters from position 2 (included) to 5 (excluded)

Py
tho


It's worth noting that for non-negative indices, the length of a slice is the difference of the indices, if both are within bounds. For example, the length of word[1:3] is 2.

Python strings cannot be changed — they are **immutable**. Therefore, assigning to an indexed position in the string results in an error:

In [17]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [ ]:
# If you need a different string, you should create a new one:
'J' + word[1:]

'Jython'

In [ ]:
# the built-in function len() returns the length of a string:
name = 'Pawel'
len(name)

5

## Lists

 The most versatile is the list, which can be written as a list of comma-separated values (items) between square brackets. <br>
 Lists might contain items of different types, but usually the items all have the same type.

In [ ]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [ ]:
# Like strings (and all other built-in sequence types), lists can be indexed and sliced:
print(squares[0])  # indexing returns the item
print(squares[-1])
print(squares[-3:])  # slicing returns a new list

1
25
[9, 16, 25]


In [ ]:
# Lists also support operations like concatenation:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
# Lists are a mutable type, i.e. it is possible to change their content:
cubes = [1, 8, 27, 65, 125]  # something's wrong here - the cube of 4 is 64, not 65!
cubes[3] = 64  # replace the wrong value
cubes

[1, 8, 27, 64, 125]

In [ ]:
# You can also add new items at the end of the list, by using the append() method (we will see more about methods later):
cubes.append(216)  # add the cube of 6
cubes.append(7 ** 3)  # and the cube of 7
cubes

[1, 8, 27, 64, 125, 216, 343]

Simple assignment in Python never copies data. When you assign a list to a variable, the variable refers to the existing list. Any changes you make to the list through one variable will be seen through all other variables that refer to it.:

In [ ]:
rgb = ["Red", "Green", "Blue"]
rgba = rgb
id(rgb) == id(rgba)  # they reference the same object

True

In [ ]:
rgba.append("Alph")
rgb

['Red', 'Green', 'Blue', 'Alph']

In [ ]:
# Assignment to slices is also possible, and this can even change the size of the list or clear it entirely:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
letters[2:5] = ['C', 'D', 'E']  # replace some values
print(letters)
letters[2:5] = []  # now remove them
print(letters)
letters[:] = []  # clear the list by replacing all the elements with an empty list
print(letters)

['a', 'b', 'C', 'D', 'E', 'f', 'g']
['a', 'b', 'f', 'g']
[]


In [ ]:
# built-in function len() also applies to lists:
len(letters)

0

In [ ]:
# we can also have nested lists
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x

[['a', 'b', 'c'], [1, 2, 3]]

## Tips

In [ ]:
# Fibonacci series:
# the sum of two elements defines the next
a, b = 0, 1
while a < 10:
    print(a)
    a, b = b, a+b

0
1
1
2
3
5
8


This example introduces several new features. <br>

The first line contains a multiple assignment: the variables a and b simultaneously get the new values 0 and 1. On the last line this is used again, demonstrating that the expressions on the right-hand side are all evaluated first before any of the assignments take place. The right-hand side expressions are evaluated from the left to the right.<br>

The while loop executes as long as the condition (here: a < 10) remains true. In Python, like in C, any non-zero integer value is true; zero is false. The condition may also be a string or list value, in fact any sequence; anything with a non-zero length is true, empty sequences are false. The test used in the example is a simple comparison. The standard comparison operators are written the same as in C: < (less than), > (greater than), == (equal to), <= (less than or equal to), >= (greater than or equal to) and != (not equal to).<br>
The body of the loop is indented: indentation is Python’s way of grouping statements. At the interactive prompt, you have to type a tab or space(s) for each indented line. In practice you will prepare more complicated input for Python with a text editor; all decent text editors have an auto-indent facility. When a compound statement is entered interactively, it must be followed by a blank line to indicate completion (since the parser cannot guess when you have typed the last line). Note that each line within a basic block must be indented by the same amount.<br>

The print() function writes the value of the argument(s) it is given. It differs from just writing the expression you want to write (as we did earlier in the calculator examples) in the way it handles multiple arguments, floating-point quantities, and strings. Strings are printed without quotes, and a space is inserted between items, so you can format things nicely, like this:

In [ ]:
i = 256*256
print('The value of i is', i)

The value of i is 65536


In [ ]:
# The keyword argument end can be used to avoid the newline after the output, or end the output with a different string:
a, b = 0, 1
while a < 1000:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

# Control Flow Tools

## if Statements

The most commonly used and well-known is the **if** statement. There can be zero or more **elif** parts and the **else** part is also optional.

In [ ]:
x = 6
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

More


It's worth noting that if we compare the same value to several constants, or we're checking for specific types or attributes we may use **match** statement.

## for Statements

The for statement in Python differs a bit from what we may be used to in C or Pascal. Rather than always iterating over an arithmetic progression of numbers (like in Pascal), or giving the user the ability to define both the iteration step and halting condition (as C), Python’s for statement iterates over the items of any sequence (a list or a string), in the order that they appear in the sequence.

In [ ]:
# Measure some strings:
words = ['cat', 'window', 'defenestrate']
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


Code that modifies a collection while iterating over that same collection can be tricky to get right. Instead, it is usually more straight-forward to loop over a copy of the collection or to create a new collection:

In [ ]:
# Create a sample collection
users = {'Hans': 'active', 'Éléonore': 'inactive', '景太郎': 'active'}

# Strategy:  Iterate over a copy
for user, status in users.copy().items():   # copy() is built-in method for making a shallow copy as well as items() is built-in method for displaying all items in a dictionary
    if status == 'inactive':
        del users[user]

# Strategy:  Create a new collection
active_users = {}
for user, status in users.items():
    if status == 'active':
        active_users[user] = status

## The range() Function

If you do need to iterate over a sequence of numbers, the built-in function **range()** comes in handy. It generates arithmetic progressions:

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


The given end point is never part of the generated sequence; range(10) generates 10 values, the legal indices for items of a sequence of length 10. It is possible to let the range start at another number, or to specify a different increment (even negative; sometimes this is called the ‘step’):

In [ ]:
print(list(range(5, 10)))
print(list(range(0, 10, 3)))
print(list(range(-10, -100, -30)))

[5, 6, 7, 8, 9]
[0, 3, 6, 9]
[-10, -40, -70]


In [ ]:
# to iterate over the indices of a sequence, you can combine range() and len() as follows:
a = ['Mary', 'had', 'a', 'little', 'lamb']
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In most such cases, however, it is convenient to use the **enumerate()** function discussed later. <br>
In many ways the object returned by range() behaves as if it is a list, but in fact it isn’t. It is an object which returns the successive items of the desired sequence when you iterate over it, but it doesn’t really make the list, thus saving space.<br>
We say such an object is iterable, that is, suitable as a target for functions and constructs that expect something from which they can obtain successive items until the supply is exhausted. We have seen that the for statement is such a construct, while an example of a function that takes an iterable is sum()

In [ ]:
sum(range(4))  # 0 + 1 + 2 + 3

6

## break and continue Statements

The **break** statement breaks out of the innermost enclosing for or while loop:

In [ ]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(f"{n} equals {x} * {n//x}")
            break

4 equals 2 * 2
6 equals 2 * 3
8 equals 2 * 4
9 equals 3 * 3


The **continue** statement continues with the next iteration of the loop:

In [ ]:
for num in range(2, 10):
    if num % 2 == 0:
        print(f"Found an even number {num}")
        continue
    print(f"Found an odd number {num}")

Found an even number 2
Found an odd number 3
Found an even number 4
Found an odd number 5
Found an even number 6
Found an odd number 7
Found an even number 8
Found an odd number 9


## else Clauses on Loops

In a for or while loop the break statement may be paired with an else clause. If the loop finishes without executing the break, the else clause executes.
<br>
In a for loop, the else clause is executed after the loop finishes its final iteration, that is, if no break occurred.
<br>
In a while loop, it’s executed after the loop’s condition becomes false.
<br>
In either kind of loop, the else clause is not executed if the loop was terminated by a break. Of course, other ways of ending the loop early, such as a return or a raised exception, will also skip execution of the else clause.
<br>
This is exemplified in the following for loop, which searches for prime numbers:

In [ ]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        # loop fell through without finding a factor
        print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


## pass Statements

The **pass** statement does nothing. It can be used when a statement is required syntactically but the program requires no action.

In [ ]:
# Commonly used for crfeating minimal classes
class MyEmptyClass:
    pass

Another place pass can be used is as a place-holder for a function or conditional body when you are working on new code, allowing you to keep thinking at a more abstract level. The pass is silently ignored:

In [ ]:
def initlog(*args):
    pass   # Remember to implement this!

## match Statements

A **match** statement takes an expression and compares its value to successive patterns given as one or more case blocks. This is superficially similar to a switch statement in C, Java or JavaScript (and many other languages), but it’s more similar to pattern matching in languages like Rust or Haskell. Only the first pattern that matches gets executed and it can also extract components (sequence elements or object attributes) from the value into variables.
<br>
The simplest form compares a subject value against one or more literals:

In [ ]:
status = 500
def http_error(status):
    match status:
        case 400:
            return print("Bad request")
        case 404:
            return print("Not found")
        case 418:
            return print("I'm a teapot")
        case _:
            return print("Something's wrong with the internet")

http_error(status)

# Note the last block: the “variable name” _ acts as a wildcard and never fails to match. If no case matches, none of the branches is executed.

Something's wrong with the internet


In [ ]:
# You can combine several literaks in a single pattern, using | ("or")as a separator:
def http_error(status):
    match status:
        case 400 | 404 | 418:
            return print("Client error")
        case 500 | 501 | 502:
            return print("Server error")
        case _:
            return print("Something's wrong with the internet")

In [ ]:
# Patterns can look like unpacking assignments and can be used to bind variables:
# point is an (x, y) tuple
point = (1, 2)
match point:
    case (0, 0):
        print("Origin")
    case (0, y):
        print(f"Y={y}")
    case (x, 0):
        print(f"X={x}")
    case (x, y):
        print(f"X={x}, Y={y}")
    case _:
        raise ValueError("Not a point")

X=1, Y=2


In [ ]:
# If you are using classes to structure your data you can use the class name followed by an argument list resembling a constructor, 
# but with the ability to capture attributes into variables:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

def where_is(point):
    match point:
        case Point(x=0, y=0):
            print("Origin")
        case Point(x=0, y=y):
            print(f"Y={y}")
        case Point(x=x, y=0):
            print(f"X={x}")
        case Point():
            print("Somewhere else")
        case _:
            print("Not a point")

A recommended way to read patterns is to look at them as an extended form of what you would put on the left of an assignment, to understand which variables would be set to what. Only the standalone names (like var above) are assigned to by a match statement. Dotted names (like foo.bar), attribute names (the x= and y= above) or class names (recognized by the “(…)” next to them like Point above) are never assigned to.
<br>
Patterns can be arbitrarily nested. For example, if we have a short list of Points, with __match_args__ added, we could match it like this:

In [ ]:
class Point:
    __match_args__ = ('x', 'y')
    def __init__(self, x, y):
        self.x = x
        self.y = y

points = [Point(0, 0), Point(1, 1), Point(0, 2), Point(0, 3), Point(4, 0)]
match points:
    case []:
        print("No points")
    case [Point(0, 0)]:
        print("The origin")
    case [Point(x, y)]:
        print(f"Single point {x}, {y}")
    case [Point(0, y1), Point(0, y2)]:
        print(f"Two on the Y axis at {y1}, {y2}")
    case _:
        print("Something else")

Something else


In [ ]:
# We can add an if clause to a pattern, known as a “guard”. 
# If the guard is false, match goes on to try the next case block. Note that value capture happens before the guard is evaluated:
match point:
    case Point(x, y) if x == y:
        print(f"Y=X at {x}")
    case Point(x, y):
        print(f"Not on the diagonal")

Several other key features of this statement:
<br><br>
Like unpacking assignments, tuple and list patterns have exactly the same meaning and actually match arbitrary sequences. An important exception is that they don’t match iterators or strings.
<br><br>
Sequence patterns support extended unpacking: [x, y, *rest] and (x, y, *rest) work similar to unpacking assignments. The name after * may also be _, so (x, y, *_) matches a sequence of at least two items without binding the remaining items.
<br><br>
Mapping patterns: {"bandwidth": b, "latency": l} captures the "bandwidth" and "latency" values from a dictionary. Unlike sequence patterns, extra keys are ignored. An unpacking like **rest is also supported. (But **_ would be redundant, so it is not allowed.)
<br><br>
Subpatterns may be captured using the as keyword:
<br><br>
case (Point(x1, y1), Point(x2, y2) as p2): ...
will capture the second element of the input as p2 (as long as the input is a sequence of two points)
<br><br>
Most literals are compared by equality, however the singletons True, False and None are compared by identity.
<br><br>
Patterns may use named constants. These must be dotted names to prevent them from being interpreted as capture variable:

In [ ]:
from enum import Enum
class Color(Enum):
    RED = 'red'
    GREEN = 'green'
    BLUE = 'blue'

color = Color(input(print("Enter your choice of 'red', 'blue' or 'green': ")))

match color:
    case Color.RED:
        print("I see red!")
    case Color.GREEN:
        print("Grass is green")
    case Color.BLUE:
        print("I'm feeling the blues :(")

Enter your choice of 'red', 'blue' or 'green': 


ValueError: '' is not a valid Color

## Defining Functions

In [ ]:
# We can create a function that writes the Fibonacci series to an arbitrary boundary:
def fib(n):    # write Fibonacci series less than n
    """Print a Fibonacci series less than n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


The keyword **def** introduces a function definition. It must be followed by the function name and the parenthesized list of formal parameters. The statements that form the body of the function start at the next line, and must be indented.

The first statement of the function body can optionally be a string literal; this string literal is the function’s documentation string, or docstring.  There are tools which use docstrings to automatically produce online or printed documentation, or to let the user interactively browse through code; it’s good practice to include docstrings in code that you write, so make a habit of it.

In fact, even functions without a return statement do return a value, albeit a rather boring one. This value is called **None** (it’s a built-in name). Writing the value None is normally suppressed by the interpreter if it would be the only value written. You can see it if you really want to using print():

In [ ]:
fib(0)
print(fib(0))



None


In [ ]:
# It is simple to write a function that returns a list of the numbers of the Fibonacci series, instead of printing it:
def fib2(n):  # return Fibonacci series up to n
    """Return a list containing the Fibonacci series up to n."""
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)    # see below
        a, b = b, a+b
    return result

f100 = fib2(100)    # call it
f100                # write the result
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

This example, as usual, demonstrates some new Python features:
<br><br>
The return statement returns with a value from a function. return without an expression argument returns None. Falling off the end of a function also returns None.
<br><br>
The statement result.append(a) calls a method of the list object result. A method is a function that ‘belongs’ to an object and is named obj.methodname, where obj is some object (this may be an expression), and methodname is the name of a method that is defined by the object’s type. Different types define different methods. Methods of different types may have the same name without causing ambiguity. (It is possible to define your own object types and methods, using classes) The method append() shown in the example is defined for list objects; it adds a new element at the end of the list. In this example it is equivalent to result = result + [a], but more efficient.

## More on Defining Functions

It is also possible to define functions with a variable number of arguments. There are three forms, which can be combined.

### Default Argument Values

The most useful form is to specify a default value for one or more arguments. This creates a function that can be called with fewer arguments than it is defined to allow. For example:

In [ ]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
    while True:
        reply = input(prompt)
        if reply in {'y', 'ye', 'yes'}:
            return True
        if reply in {'n', 'no', 'nop', 'nope'}:
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)

This function can be called in several ways:

- giving only the mandatory argument: ask_ok('Do you really want to quit?')

- giving one of the optional arguments: ask_ok('OK to overwrite the file?', 2)

- or even giving all arguments: ask_ok('OK to overwrite the file?', 2, 'Come on, only yes or no!')
<br><br>
This example also introduces the **in** keyword. This tests whether or not a sequence contains a certain value.

In [ ]:
# The default values are evaluated at the point of function definition in the defining scope, so that
i = 5

def f(arg=i):
    print(arg)

i = 6
f()

5


**Important warning:** The default value is evaluated only once. This makes a difference when the default is a mutable object such as a list, dictionary, or instances of most classes. For example, the following function accumulates the arguments passed to it on subsequent calls:

In [ ]:
def f(a, L=[]):
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

[1]
[1, 2]
[1, 2, 3]


In [ ]:
# If you don’t want the default to be shared between subsequent calls, you can write the function like this instead:
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

[1]
[2]
[3]


### Keyword Arguments

Functions can also be called using keyword arguments of the form kwarg=value. For instance, the following function:

In [ ]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

accepts one required argument (voltage) and three optional arguments (state, action, and type). This function can be called in any of the following ways:

In [ ]:
parrot(1000)                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !
-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


In [ ]:
# But all the following calls are invalid:

#parrot()                     # required argument missing
#parrot(voltage=5.0, 'dead')  # non-keyword argument after a keyword argument
#parrot(110, voltage=220)     # duplicate value for the same argument
#parrot(actor='John Cleese')  # unknown keyword argument

In a function call, keyword arguments must follow positional arguments. All the keyword arguments passed must match one of the arguments accepted by the function (e.g. actor is not a valid argument for the parrot function), and their order is not important. This also includes non-optional arguments (e.g. parrot(voltage=1000) is valid too). No argument may receive a value more than once.

### Special parameters

By default, arguments may be passed to a Python function either by position or explicitly by keyword. For readability and performance, it makes sense to restrict the way arguments can be passed so that a developer need only look at the function definition to determine if items are passed by position, by position or keyword, or by keyword.

A function definition may look like:

In [ ]:
"""def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):
      -----------    ----------     ----------
        |             |                  |
        |        Positional or keyword   |
        |                                - Keyword only
         -- Positional only"""

'def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):\n      -----------    ----------     ----------\n        |             |                  |\n        |        Positional or keyword   |\n        |                                - Keyword only\n         -- Positional only'

where **/** and * are optional. If used, these symbols indicate the kind of parameter by how the arguments may be passed to the function: positional-only, positional-or-keyword, and keyword-only. Keyword parameters are also referred to as named parameters.

#### Positional-or-Keyword Arguments

If / and * are not present in the function definition, arguments may be passed to a function by position or by keyword.

#### Positional-Only Parameters

Looking at this in a bit more detail, it is possible to mark certain parameters as positional-only. If positional-only, the parameters’ order matters, and the parameters cannot be passed by keyword. Positional-only parameters are placed before a / (forward-slash). The / is used to logically separate the positional-only parameters from the rest of the parameters. If there is no / in the function definition, there are no positional-only parameters.

Parameters following the / may be positional-or-keyword or keyword-only.

#### Keyword-Only Arguments

To mark parameters as keyword-only, indicating the parameters must be passed by keyword argument, place an * in the arguments list just before the first keyword-only parameter.

#### Function Examples

In [ ]:
def standard_arg(arg):
    print(arg)

def pos_only_arg(arg, /):
    print(arg)

def kwd_only_arg(*, arg):
    print(arg)

def combined_example(pos_only, /, standard, *, kwd_only):
    print(pos_only, standard, kwd_only)

In [ ]:
# The first function definition, standard_arg, the most familiar form, 
# places no restrictions on the calling convention and arguments may be passed by position or keyword:
standard_arg(2)
standard_arg(arg=2)

2
2


In [ ]:
# The second function pos_only_arg is restricted to only use positional parameters as there is a / in the function definition:
pos_only_arg(1)
#pos_only_arg(arg=1) <-- would cause an error!!

1


In [ ]:
# The third function kwd_only_arg only allows keyword arguments as indicated by a * in the function definition:
kwd_only_arg(arg=3)
#kwd_only_arg(3) <-- would cause an error!!

3


In [ ]:
# And the last uses all three calling conventions in the same function definition:
combined_example(1, 2, kwd_only=3)
#combined_example(1, standard=2, kwd_only=3) <-- would cause an error!!
#combined_example(1, 2, 3) <-- would cause an error!!

1 2 3


#### Recap

In [ ]:
# The use case will determine which parameters to use in the function definition:

def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):
    print(pos1, pos2, pos_or_kwd, kwd1, kwd2)

As guidance:

- Use positional-only if you want the name of the parameters to not be available to the user. This is useful when parameter names have no real meaning, if you want to enforce the order of the arguments when the function is called or if you need to take some positional parameters and arbitrary keywords.

- Use keyword-only when names have meaning and the function definition is more understandable by being explicit with names or you want to prevent users relying on the position of the argument being passed.

- For an API, use positional-only to prevent breaking API changes if the parameter’s name is modified in the future.

### Arbitrary Argument Lists

Finally, the least frequently used option is to specify that a function can be called with an arbitrary number of arguments. These arguments will be wrapped up in a tuple. Before the variable number of arguments, zero or more normal arguments may occur.

In [ ]:
def write_multiple_items(file, separator, *args):
    file.write(separator.join(args))

Normally, these variadic arguments will be last in the list of formal parameters, because they scoop up all remaining input arguments that are passed to the function. Any formal parameters which occur after the *args parameter are ‘keyword-only’ arguments, meaning that they can only be used as keywords rather than positional arguments.

### Unpacking Argument Lists

The reverse situation occurs when the arguments are already in a list or tuple but need to be unpacked for a function call requiring separate positional arguments. For instance, the built-in range() function expects separate start and stop arguments. If they are not available separately, write the function call with the * -operator to unpack the arguments out of a list or tuple:

In [ ]:
list(range(3, 6))            # normal call with separate arguments
args = [3, 6]
list(range(*args))  

[3, 4, 5]

In the same fashion, dictionaries can deliver keyword arguments with the ** -operator:

In [ ]:
def parrot(voltage, state='a stiff', action='voom'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.", end=' ')
    print("E's", state, "!")

d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}
parrot(**d)

-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !


### Lambda Expressions

Small anonymous functions can be created with the lambda keyword. This function returns the sum of its two arguments: lambda a, b: a+b. Lambda functions can be used wherever function objects are required. They are syntactically restricted to a single expression. Semantically, they are just syntactic sugar for a normal function definition. Like nested function definitions, lambda functions can reference variables from the containing scope:

In [ ]:
def make_incrementor(n):
    return lambda x: x + n

f = make_incrementor(42)
f(0)

42

The above example uses a lambda expression to return a function. Another use is to pass a small function as an argument:

In [ ]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
pairs.sort(key=lambda pair: pair[1])
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

### Documentation Strings

Here are some conventions about the content and formatting of documentation strings.

The first line should always be a short, concise summary of the object’s purpose. For brevity, it should not explicitly state the object’s name or type, since these are available by other means (except if the name happens to be a verb describing a function’s operation). This line should begin with a capital letter and end with a period.

If there are more lines in the documentation string, the second line should be blank, visually separating the summary from the rest of the description. The following lines should be one or more paragraphs describing the object’s calling conventions, its side effects, etc.

The Python parser does not strip indentation from multi-line string literals in Python, so tools that process documentation have to strip indentation if desired. This is done using the following convention. The first non-blank line after the first line of the string determines the amount of indentation for the entire documentation string. (We can’t use the first line since it is generally adjacent to the string’s opening quotes so its indentation is not apparent in the string literal.) Whitespace “equivalent” to this indentation is then stripped from the start of all lines of the string. Lines that are indented less should not occur, but if they occur all their leading whitespace should be stripped. Equivalence of whitespace should be tested after expansion of tabs (to 8 spaces, normally).

Here is an example of a multi-line docstring:

In [ ]:
def my_function():
    """Do nothing, but document it.

    No, really, it doesn't do anything.
    """
    pass

print(my_function.__doc__)

Do nothing, but document it.

No, really, it doesn't do anything.



### Function Annotations

Annotations are stored in the __annotations__ attribute of the function as a dictionary and have no effect on any other part of the function. Parameter annotations are defined by a colon after the parameter name, followed by an expression evaluating to the value of the annotation. Return annotations are defined by a literal ->, followed by an expression, between the parameter list and the colon denoting the end of the def statement. The following example has a required argument, an optional argument, and the return value annotated:

In [ ]:
def f(ham: str, eggs: str = 'eggs') -> str:
    print("Annotations:", f.__annotations__)
    print("Arguments:", ham, eggs)
    return ham + ' and ' + eggs

f('spam')

Annotations: {'ham': <class 'str'>, 'eggs': <class 'str'>, 'return': <class 'str'>}
Arguments: spam eggs


'spam and eggs'

## Coding Style

For Python, PEP 8 has emerged as the style guide that most projects adhere to; it promotes a very readable and eye-pleasing coding style. Every Python developer should read it at some point; here are the most important points extracted for you:

- Use 4-space indentation, and no tabs.

- 4 spaces are a good compromise between small indentation (allows greater nesting depth) and large indentation (easier to read). Tabs introduce confusion, and are best left out.

- Wrap lines so that they don’t exceed 79 characters.

- This helps users with small displays and makes it possible to have several code files side-by-side on larger displays.

- Use blank lines to separate functions and classes, and larger blocks of code inside functions.

- When possible, put comments on a line of their own.

- Use docstrings.

- Use spaces around operators and after commas, but not directly inside bracketing constructs: a = f(1, 2) + g(3, 4).

- Name your classes and functions consistently; the convention is to use UpperCamelCase for classes and lowercase_with_underscores for functions and methods. Always use self as the name for the first method argument (see A First Look at Classes for more on classes and methods).

- Don’t use fancy encodings if your code is meant to be used in international environments. Python’s default, UTF-8, or even plain ASCII work best in any case.

- Likewise, don’t use non-ASCII characters in identifiers if there is only the slightest chance people speaking a different language will read or maintain the code.

# Data Structures

## Lists

Here are all of the methods of list objects:

**list.append(x)**
Add an item to the end of the list. Similar to a[len(a):] = [x].

**list.extend(iterable)**
Extend the list by appending all the items from the iterable. Similar to a[len(a):] = iterable.

**list.insert(i, x)**
Insert an item at a given position. The first argument is the index of the element before which to insert, so a.insert(0, x) inserts at the front of the list, and a.insert(len(a), x) is equivalent to a.append(x).

**list.remove(x)**
Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

**list.pop([i])**
Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes and returns the last item in the list. It raises an IndexError if the list is empty or the index is outside the list range.

**list.clear()**
Remove all items from the list. Similar to del a[:].

**list.index(x[, start[, end]])**
Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there is no such item.
The optional arguments start and end are interpreted as in the slice notation and are used to limit the search to a particular subsequence of the list. The returned index is computed relative to the beginning of the full sequence rather than the start argument.

**list.count(x)**
Return the number of times x appears in the list.

**list.sort(*, key=None, reverse=False)**
Sort the items of the list in place (the arguments can be used for sort customization, see sorted() for their explanation).

**list.reverse()**
Reverse the elements of the list in place.

list.copy()
Return a shallow copy of the list. Similar to a[:].

In [ ]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(fruits.count('apple'))
print(fruits.count('tangerine'))
print(fruits.index('banana'))
print(fruits.index('banana', 4))  # Find next banana starting a position 4
print(fruits.reverse())
fruits
print(fruits.append('grape'))
fruits
print(fruits.sort())
fruits
print(fruits.pop())

2
0
3
6
None
None
None
pear


You might have noticed that methods like insert, remove or sort that only modify the list have no return value printed – they return the default None. This is a design principle for all mutable data structures in Python.

Another thing you might notice is that not all data can be sorted or compared. For instance, [None, 'hello', 10] doesn’t sort because integers can’t be compared to strings and None can’t be compared to other types. Also, there are some types that don’t have a defined ordering relation. For example, 3+4j < 5+7j isn’t a valid comparison.

### Using Lists as Stacks

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use append(). To retrieve an item from the top of the stack, use pop() without an explicit index. For example:

In [ ]:
stack = [3, 4, 5]
stack.append(6)
stack.append(7)
print(stack)
stack.pop()
print(stack)
stack.pop()
print(stack)
stack.pop()
print(stack)

[3, 4, 5, 6, 7]
[3, 4, 5, 6]
[3, 4, 5]
[3, 4]


### Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“first-in, first-out”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

To implement a queue, use **collections.deque** which was designed to have fast appends and pops from both ends. For example:

In [ ]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")           # Terry arrives
queue.append("Graham")          # Graham arrives
queue.popleft()                 # The first to arrive now leaves
queue.popleft()                 # The second to arrive now leaves
queue                           # Remaining queue in order of arrival

deque(['Michael', 'Terry', 'Graham'])

### List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

For example, assume we want to create a list of squares, like:

In [ ]:
squares = []
for x in range(10):
    squares.append(x**2)

squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Note that this creates (or overwrites) a variable named x that still exists after the loop completes. We can calculate the list of squares without any side effects using:

In [ ]:
squares = list(map(lambda x: x**2, range(10)))
print(squares)

# or, equivalently:

squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


A list comprehension consists of brackets containing an expression followed by a for clause, then zero or more for or if clauses. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. For example, this listcomp combines the elements of two lists if they are not equal:

In [ ]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]


In [ ]:
# The above code is equivalent to:
# Note the order of "for" and "if" statements is teh same
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [ ]:
# Comprehension
vec = [-4, -2, 0, 2, 4]
# create a new list with the values doubled
print([x*2 for x in vec])

# filter the list to exclude negative numbers
print([x for x in vec if x >= 0])

# apply a function to all the elements
print([abs(x) for x in vec])

# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
print([weapon.strip() for weapon in freshfruit])

# create a list of 2-tuples like (number, square)
print([(x, x**2) for x in range(6)])

[-8, -4, 0, 4, 8]
[0, 2, 4]
[4, 2, 0, 2, 4]
['banana', 'loganberry', 'passion fruit']
[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]


In [ ]:
# Lists can contain complex expressions and nested functions:
from math import pi
print([str(round(pi, i)) for i in range(1, 6)])

['3.1', '3.14', '3.142', '3.1416', '3.14159']


### Nested List Comprehensions

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

Consider the following example of a 3x4 matrix implemented as a list of 3 lists of length 4:

In [ ]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

In [ ]:
# The following list comprehension will transpose rows and columns:

print([[row[i] for row in matrix] for i in range(4)])

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


As seen in the previous section, the inner list comprehension is evaluated in the context of the for that follows it, so this example is equivalent to:

In [ ]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [ ]:
# Which in turn is also the same as:
transposed = []
for i in range(4):
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In the real world, we should prefer built-in functions to complex flow statements. The zip() function would do a great job for this use case:

In [ ]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

## The del statement

There is a way to remove an item from a list given its index instead of its value: the **del** statement. This differs from the pop() method which returns a value. The del statement can also be used to remove slices from a list or clear the entire list (which we did earlier by assignment of an empty list to the slice).

In [ ]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
print(a)

del a[2:4]
print(a)

del a[:]
print(a)

[1, 66.25, 333, 333, 1234.5]
[1, 66.25, 1234.5]
[]


In [ ]:
#del can also be used to delete entire variables:
del a

## Tuples and Sequences

We saw that lists and strings have many common properties, such as indexing and slicing operations. They are two examples of sequence data types. Since Python is an evolving language, other sequence data types may be added. There is also another standard sequence data type: the tuple.

A tuple consists of a number of values separated by commas, for instance:

In [ ]:
t = 12345, 54321, 'hello!'
print(t[0])

# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
print(u)

# Tuples are immutable:
# t[0] = 88888 <- error!

# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
v

12345
((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))


([1, 2, 3], [3, 2, 1])

Though tuples may seem similar to lists, they are often used in different situations and for different purposes. Tuples are immutable, and usually contain a heterogeneous sequence of elements that are accessed via unpacking or indexing (or even by attribute in the case of namedtuples). Lists are mutable, and their elements are usually homogeneous and are accessed by iterating over the list.

A special problem is the construction of tuples containing 0 or 1 items: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parentheses). Ugly, but effective. For example:

In [ ]:
empty = ()
singleton = 'hello',    # <-- note trailing comma
print(len(empty))

print(len(singleton))

singleton

0
1


('hello',)

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple. The reverse operation is also possible:

In [ ]:
x, y, z = t

# This is called sequence unpacking and works for any sequence on the righ-hand side.

## Sets

Python also includes a data type for sets. **A set is an unordered collection with no duplicate elements**. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary.

In [ ]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # show that duplicates have been removed
{'orange', 'banana', 'pear', 'apple'}

print('orange' in basket)                 # fast membership testing

print('crabgrass' in basket)


# Demonstrate set operations on unique letters from two words

a = set('abracadabra')
b = set('alacazam')
print(a)                                  # unique letters in a

print(a - b)                              # letters in a but not in b

print(a | b)                              # letters in a or b or both

print(a & b)                              # letters in both a and b

print(a ^ b)                              # letters in a or b but not both


{'orange', 'banana', 'apple', 'pear'}
True
False
{'r', 'c', 'a', 'd', 'b'}
{'r', 'd', 'b'}
{'r', 'c', 'a', 'l', 'z', 'm', 'd', 'b'}
{'c', 'a'}
{'m', 'r', 'd', 'b', 'l', 'z'}


In [ ]:
# Similarly to list comprehensions, set comprehensions are also supported:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

## Dictionaries

Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like append() and extend().

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with del. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing **list(d)** on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use **sorted(d)** instead). To check whether a single key is in the dictionary, use the **in** keyword.

In [ ]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
print(tel)

print(tel['jack'])

del tel['sape']
tel['irv'] = 4127
print(tel)

print(list(tel))

print(sorted(tel))

print('guido' in tel)

'jack' not in tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}
4098
{'jack': 4098, 'guido': 4127, 'irv': 4127}
['jack', 'guido', 'irv']
['guido', 'irv', 'jack']
True


False

The **dict()** constructor builds dictionaries directly from sequences of key-value pairs:

In [ ]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [ ]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [ ]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

## Looping Techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the **items()** method.

In [ ]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


When looping through a sequence, the position index and corresponding value can be retrieved at the same time using the **enumerate()** function.

In [ ]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


To loop over two or more sequences at the same time, the entries can be paired with the **zip()** function.

In [ ]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the **reversed()** function.

In [ ]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


To loop over a sequence in sorted order, use the **sorted()** function which returns a new sorted list while leaving the source unaltered.

In [ ]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for i in sorted(basket):
    print(i)

apple
apple
banana
orange
orange
pear


Using **set()** on a sequence eliminates duplicate elements. The use of **sorted()** in combination with **set()** over a sequence is an idiomatic way to loop over unique elements of the sequence in sorted order.

In [ ]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [ ]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

## More on Conditions

The conditions used in while and if statements can contain any operators, not just comparisons.

The comparison operators **in** and **not in** are membership tests that determine whether a value is in (or not in) a container. The operators **is** and **is not** compare whether two objects are really the same object. All comparison operators have the same priority, which is lower than that of all numerical operators.

Comparisons can be chained. For example, **a < b == c** tests whether **a** is less than **b** and moreover **b** equals **c**.

Comparisons may be combined using the Boolean operators **and** and **or**, and the outcome of a comparison (or of any other Boolean expression) may be negated with **not**. These have lower priorities than comparison operators; between them, **not** has the highest priority and **or** the lowest, so that **A and not B or C** is equivalent to **(A and (not B)) or C**. As always, parentheses can be used to express the desired composition.

The Boolean operators **and** and **or** are so-called short-circuit operators: their arguments are evaluated from left to right, and evaluation stops as soon as the outcome is determined. For example, if **A** and **C** are true but **B** is false, **A and B and C** does not evaluate the expression C. When used as a general value and not as a Boolean, the return value of a short-circuit operator is the last evaluated argument.

In [18]:
# It is possible to assign the result of a comparison or other Boolean expression to a variable.

string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'
non_null = string1 or string2 or string3
non_null

'Trondheim'

## Comparing Sequences and Other Types

Sequence objects typically may be compared to other objects with the same sequence type. The comparison uses lexicographical ordering: first the first two items are compared, and if they differ this determines the outcome of the comparison; if they are equal, the next two items are compared, and so on, until either sequence is exhausted. If two items to be compared are themselves sequences of the same type, the lexicographical comparison is carried out recursively. If all items of two sequences compare equal, the sequences are considered equal. If one sequence is an initial sub-sequence of the other, the shorter sequence is the smaller (lesser) one. Lexicographical ordering for strings uses the Unicode code point number to order individual characters.

In [20]:
print((1, 2, 3)              < (1, 2, 4))
print([1, 2, 3]              < [1, 2, 4])
print('ABC' < 'C' < 'Pascal' < 'Python')
print((1, 2, 3, 4)           < (1, 2, 4))
print((1, 2)                 < (1, 2, -1))
print((1, 2, 3)             == (1.0, 2.0, 3.0))
(1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4)

True
True
True
True
True
True


True

Note that comparing objects of different types with < or > is legal provided that the objects have appropriate comparison methods. For example, mixed numeric types are compared according to their numeric value, so 0 equals 0.0, etc. Otherwise, rather than providing an arbitrary ordering, the interpreter will raise a **TypeError** exception.

# 6. Modules

Python has a way to put definitions in a file and use them in a script or in an interactive instance of the interpreter. Such a file is called a **module**; definitions from a module can be imported into other modules or into the main module (the collection of variables that you have access to in a script executed at the top level and in calculator mode).

A module is a file containing Python definitions and statements.

The file name is the module name with the suffix .py appended. Within a module, the module’s name (as a string) is available as the value of the global variable "__name__".

## More on Modules

A module can contain executable statements as well as function definitions. These statements are intended to initialize the module. They are executed only the first time the module name is encountered in an import statement. (They are also run if the file is executed as a script.)

Each module has its own private namespace, which is used as the global namespace by all functions defined in the module. Thus, the author of a module can use global variables in the module without worrying about accidental clashes with a user’s global variables. On the other hand, if you know what you are doing you can touch a module’s global variables with the same notation used to refer to its functions, **modname.itemname**.

Modules can import other modules. It is customary but not required to place all import statements at the beginning of a module (or script, for that matter). The imported module names, if placed at the top level of a module (outside any functions or classes), are added to the module’s global namespace.

There is a variant of the import statement that imports names from a module directly into the importing module’s namespace. For example:

In [21]:
# from fibo import fib, fib2 <- would not work in this environment, but would work in a python script if we had a module named fibo.py

This does not introduce the module name from which the imports are taken in the local namespace (so in the example, fibo is not defined).

There is even a variant to import all names that a module defines:

In [22]:
# from fibo import * <- would import all names except those beginning with an underscore (_)

 In most cases Python programmers do not use this facility since it introduces an unknown set of names into the interpreter, possibly hiding some things you have already defined.

If the module name is followed by **as**, then the name following as is bound directly to the imported module.

In [23]:
# import fibo as fib <- would import the module fibo and give it the name fib

In [24]:
# It can also be used when utilising from with similar effects:

# from fibo import fib as fibonacci <- would import the function fib() from the fibo module and give it the name fibonacci

### Compiled Python files

To speed up loading modules, Python caches the compiled version of each module in the __pycache__ directory under the name **module.version.pyc**, where the version encodes the format of the compiled file; it generally contains the Python version number. For example, in CPython release 3.3 the compiled version of spam.py would be cached as **_ pycache _/spam.cpython-33.pyc**. This naming convention allows compiled modules from different releases and different versions of Python to coexist.

Python checks the modification date of the source against the compiled version to see if it’s out of date and needs to be recompiled. This is a completely automatic process. Also, the compiled modules are platform-independent, so the same library can be shared among systems with different architectures.

Python does not check the cache in two circumstances. First, it always recompiles and does not store the result for the module that’s loaded directly from the command line. Second, it does not check the cache if there is no source module. To support a non-source (compiled only) distribution, the compiled module must be in the source directory, and there must not be a source module.

## Standard Modules

Python comes with a library of standard modules, described in a separate document, the Python Library Reference (“Library Reference” hereafter). Some modules are built into the interpreter; these provide access to operations that are not part of the core of the language but are nevertheless built in, either for efficiency or to provide access to operating system primitives such as system calls. The set of such modules is a configuration option which also depends on the underlying platform. For example, the winreg module is only provided on Windows systems. One particular module deserves some attention: sys, which is built into every Python interpreter. The variables **sys.ps1** and **sys.ps2** define the strings used as primary and secondary prompts.

These two variables are only defined if the interpreter is in interactive mode.

The variable **sys.path** is a list of strings that determines the interpreter’s search path for modules. It is initialized to a default path taken from the environment variable **PYTHONPATH**, or from a built-in default if PYTHONPATH is not set.

## The dir() Function

The built-in function dir() is used to find out which names a module defines. It returns a sorted list of strings:

In [25]:
# import fibo, sys
# dir(fibo)
# ['__name__', 'fib', 'fib2']
# dir(sys)
# ['__breakpointhook__', '__displayhook__', '__doc__', '__excepthook__',
#  '__interactivehook__', '__loader__', '__name__', '__package__', '__spec__',
#  '__stderr__', '__stdin__', '__stdout__', '__unraisablehook__',
#  '_clear_type_cache', '_current_frames', '_debugmallocstats', '_framework',
#  '_getframe', '_git', '_home', '_xoptions', 'abiflags', 'addaudithook',
#  'api_version', 'argv', 'audit', 'base_exec_prefix', 'base_prefix',
#  'breakpointhook', 'builtin_module_names', 'byteorder', 'call_tracing',
#  'callstats', 'copyright', 'displayhook', 'dont_write_bytecode', 'exc_info',
#  'excepthook', 'exec_prefix', 'executable', 'exit', 'flags', 'float_info',
#  'float_repr_style', 'get_asyncgen_hooks', 'get_coroutine_origin_tracking_depth',
#  'getallocatedblocks', 'getdefaultencoding', 'getdlopenflags',
#  'getfilesystemencodeerrors', 'getfilesystemencoding', 'getprofile',
#  'getrecursionlimit', 'getrefcount', 'getsizeof', 'getswitchinterval',
#  'gettrace', 'hash_info', 'hexversion', 'implementation', 'int_info',
#  'intern', 'is_finalizing', 'last_traceback', 'last_type', 'last_value',
#  'maxsize', 'maxunicode', 'meta_path', 'modules', 'path', 'path_hooks',
#  'path_importer_cache', 'platform', 'prefix', 'ps1', 'ps2', 'pycache_prefix',
#  'set_asyncgen_hooks', 'set_coroutine_origin_tracking_depth', 'setdlopenflags',
#  'setprofile', 'setrecursionlimit', 'setswitchinterval', 'settrace', 'stderr',
#  'stdin', 'stdout', 'thread_info', 'unraisablehook', 'version', 'version_info',
#  'warnoptions']

Without arguments, dir() lists the names you have defined currently:

In [26]:
a = [1, 2, 3, 4, 5]

dir()

['In',
 'Out',
 '_',
 '_1',
 '_12',
 '_13',
 '_14',
 '_18',
 '_19',
 '_2',
 '_20',
 '_3',
 '_4',
 '_5',
 '_6',
 '_7',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a',
 'exit',
 'get_ipython',
 'non_null',
 'open',
 'quit',
 's',
 'string1',
 'string2',
 'string3',
 'word']

Note that it lists all types of names: variables, modules, functions, etc.

dir() does not list the names of built-in functions and variables. If you want a list of those, they are defined in the standard module **builtins**:

In [27]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BaseExceptionGroup',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EncodingWarning',
 'EnvironmentError',
 'Exception',
 'ExceptionGroup',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'PythonFinalizationError',
 'RecursionError',
 'ReferenceError',

## Packages

Packages are a way of structuring Python’s module namespace by using “dotted module names”. For example, the module name **A.B** designates a submodule named **B** in a package named **A**. Just like the use of modules saves the authors of different modules from having to worry about each other’s global variable names, the use of dotted module names saves the authors of multi-module packages like NumPy or Pillow from having to worry about each other’s module names.

Suppose you want to design a collection of modules (a “package”) for the uniform handling of sound files and sound data. There are many different sound file formats (usually recognized by their extension, for example: .wav, .aiff, .au), so you may need to create and maintain a growing collection of modules for the conversion between the various file formats. There are also many different operations you might want to perform on sound data (such as mixing, adding echo, applying an equalizer function, creating an artificial stereo effect), so in addition you will be writing a never-ending stream of modules to perform these operations. Here’s a possible structure for your package (expressed in terms of a hierarchical filesystem):

In [36]:
# sound/                          Top-level package
#       __init__.py               Initialize the sound package
#       formats/                  Subpackage for file format conversions
#               __init__.py
#               wavread.py
#               wavwrite.py
#               aiffread.py
#               aiffwrite.py
#               auread.py
#               auwrite.py
#               ...
#       effects/                  Subpackage for sound effects
#               __init__.py
#               echo.py
#               surround.py
#               reverse.py
#               ...
#       filters/                  Subpackage for filters
#               __init__.py
#               equalizer.py
#               vocoder.py
#               karaoke.py
#               ...

When importing the package, Python searches through the directories on sys.path looking for the package subdirectory.

The __init__.py files are required to make Python treat directories containing the file as packages (unless using a namespace package, a relatively advanced feature). This prevents directories with a common name, such as string, from unintentionally hiding valid modules that occur later on the module search path. In the simplest case, __init__.py can just be an empty file, but it can also execute initialization code for the package or set the __all__ variable, described later.

In [33]:
# Users of the package can import individual modules from the package, for example:

# import sound.effects.echo

In [34]:
# This loads the submodule sound.effects.echo. It must be referenced with its full name.

# sound.effects.echo.echofilter(input, output, delay=0.7, atten=4)

In [35]:
# An alternative way of importing the submodule is:

# from sound.effects import echo

In [40]:
# This also loads the submodule echo, and makes it available without its package prefix, so it can be used as follows:
# echo.echofilter(input, output, delay=0.7, atten=4)

# Yet another variation is to import the desired function or variable directly:
# from sound.effects.echo import echofilter

# Again, this loads the submodule echo, but this makes its function echofilter() directly available:
# echofilter(input, output, delay=0.7, atten=4)

Note that when using **from package import item**, the item can be either a submodule (or subpackage) of the package, or some other name defined in the package, like a function, class or variable. The **import** statement first tests whether the item is defined in the package; if not, it assumes it is a module and attempts to load it. If it fails to find it, an **ImportError** exception is raised.

Contrarily, when using syntax like **import item.subitem.subsubitem**, each item except for the last must be a package; the last item can be a module or a package but can’t be a class or function or variable defined in the previous item.

### Importing * From a Package

Now what happens when the user writes from sound.effects import *? Ideally, one would hope that this somehow goes out to the filesystem, finds which submodules are present in the package, and imports them all. This could take a long time and importing sub-modules might have unwanted side-effects that should only happen when the sub-module is explicitly imported.

The only solution is for the package author to provide an explicit index of the package. The **import** statement uses the following convention: if a package’s **__init__.py** code defines a list named __all__, it is taken to be the list of module names that should be imported when **from package import *** is encountered. It is up to the package author to keep this list up-to-date when a new version of the package is released. Package authors may also decide not to support it, if they don’t see a use for importing * from their package. For example, the file sound/effects/__init__.py could contain the following code:

In [41]:
# __all__ = ["echo", "surround", "reverse"]

This would mean that from sound.effects import * would import the three named submodules of the sound.effects package.

# Input and Output